# R for Travis CI: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
r: devel
cache: packages

notifications:
  email: false

env:
  matrix: 
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

script: 
  - R CMD build .
    R CMD check rstanjm*tar.gz  
  
after_script:
  - tar -ztvf rstanjm_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - tar -C .. -xf $PKG_TARBALL

after_failure:
  - cat rstanjm.Rcheck/00*
